# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
platform :ios do
  desc "TestFlight 배포 자동화"
  lane :beta do
    increment_build_number(xcodeproj: "UnivApp.xcodeproj")
    build_app(scheme: "UnivApp")
    upload_to_testflight
    slack(
       message: "TestFlight 배포 완료",
       webhook: "https://hooks.slack.com/services/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"
    )
  end
end
